name: Yad2 Scraper

on:
  schedule:
    - cron: "*/5 5-20 * * *" # Run every half hour between 08:00-23:00 Israel Time (UTC 5:00-20:00)
  workflow_dispatch:
    branches:
      - "**"

jobs:
  scraper:
    runs-on: ubuntu-22.04 # Updated to a specific version for consistency and possibly lower cost
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Updated to the latest stable version

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "Bun installed successfully."

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies using Bun
        run: |
          ~/.bun/bin/bun install
          echo "Dependencies installed successfully."

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "${{ secrets.GIT_CONFIG_EMAIL }}"

      - name: Run scraper
        id: scraper # Added ID to reference this step in the following steps
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          ~/.bun/bin/bun run scrape
          echo "Scraper run completed successfully."

      - name: Push new JSON data if needed
        if: success() && steps.scraper.outcome == 'success' # Only run if previous steps were successful
        run: |
          if [ -f ./push_me ]; then
            echo "Changes detected, pushing to GitHub..."
            git add .
            DATE=$(date +"%F, %H:%M:%S")
            git commit -m "updated data - $DATE"
            git push
          else
            echo "No changes to push."
        shell: bash -l
