name: Scraper Workflow

on:
  schedule:
    - cron: '*/30 5-20 * * *'
  workflow_dispatch:
    branches:
      - '**'

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-bun-

      - name: Setup Git Configuration
        run: |
          echo "Setting up Git Configuration..."
          git config --global user.name "GitHub Actions"
          git config --global user.email "${{ secrets.GIT_CONFIG_EMAIL }}"
          echo "Git configuration completed"

      - name: Run Bun Start
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          echo "Running Bun Start..."
          bun start
          echo "Bun script execution completed"

      - name: Check for push_me and Push Changes
        if: success() && ("${{ github.workspace }}/push_me" != '')
        run: |
          if [ -f "${{ github.workspace }}/push_me" ]; then
            echo "push_me file detected, proceeding with Git operations..."
            git add .
            DATE=$(date)
            git commit -m "updated data - $DATE"
            git push
          else
            echo "push_me file not found. Skipping Git operations."
          fi